global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

scrape_configs:
  - job_name: 'expressjs-app'
    static_configs:
      - targets: ['192.168.50.90:3000']
    scheme: http